[rust]
edition = "2021"   #åœ¨çº¿è¿è¡Œç”¨2021ç‰ˆæœ¬çš„

[book]
authors = ["sunface"]
language = "zh-CN"
title = "Rustè¯­è¨€åœ£ç»(Rust Course)"
src = "src"

[output.html]
additional-css = ["theme/style.css"]
additional-js = ["assets/custom.js", "assets/bigPicture.js"]
git-repository-url = "https://github.com/sunface/rust-course"
edit-url-template = "https://github.com/sunface/rust-course/edit/main/{path}"
#theme = ["theme"]  # ğŸ‘ˆ åŠ è¿™ä¸€è¡Œï¼Œå¯ç”¨è‡ªå®šä¹‰ HTML æ¨¡æ¿


[output.html.playground]
editable = true
copy-js = true
# line-numbers = true

[output.html.fold]
enable = true
level = 0
